### ISSUE TITLE
Deploy website *after* merging code

### ISSUE THREAD

**Issue by aalbaali** [aalbaali/aalbaali.github.io#4]
Move
```yaml
- name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: __site

```
To a separate workflow that is activated *after* the code is merged into the `main` branch.
